# Generated by Django 4.0.3 on 2022-03-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_whyus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whyus',
            options={'ordering': ('number',)},
        ),
    ]
