# Generated by Django 4.0.3 on 2022-03-08 19:41

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_whyus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desc', models.TextField(max_length=300)),
                ('first_check', models.TextField(max_length=200, unique=True)),
                ('second_check', models.TextField(blank=True, max_length=200, unique=True)),
                ('third_check', models.TextField(blank=True, max_length=200, unique=True)),
                ('last_word', models.TextField(max_length=200)),
                ('photo', models.ImageField(upload_to=main_page.models.Events.get_file_name_events)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
