# Generated by Django 4.0.3 on 2022-03-09 13:30

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('spec', models.CharField(max_length=40, unique=True)),
                ('photo', models.ImageField(upload_to=main_page.models.Chefs.get_file_name_chefs)),
                ('twitter', models.CharField(max_length=50, unique=True)),
                ('facebook', models.CharField(max_length=50, unique=True)),
                ('insta', models.CharField(max_length=50, unique=True)),
                ('linkedin', models.CharField(max_length=50, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='first_check',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='second_check',
            field=models.TextField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='third_check',
            field=models.TextField(blank=True, max_length=100, unique=True),
        ),
    ]
