# Generated by Django 4.0.3 on 2022-03-09 14:07

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_chefs_alter_events_desc_alter_events_first_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
                ('speciality', models.CharField(max_length=50, unique=True)),
                ('whatsaid', models.TextField(max_length=500)),
                ('photo', models.ImageField(upload_to=main_page.models.Testimonials.get_file_name_testimonials)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
