# Generated by Django 4.0.3 on 2022-03-11 16:14

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
                ('photo', models.ImageField(upload_to=main_page.models.Gallery.get_file_name_gallery)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
