# Generated by Django 4.0.3 on 2022-03-11 18:12

from django.db import migrations
import django_resized.forms
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[800, 600], upload_to=main_page.models.Gallery.get_file_name_gallery),
        ),
    ]
