# Generated by Django 4.0.3 on 2022-03-13 11:18

import django.core.validators
from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_alter_gallery_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookATable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone in format xxx xxx xxxx', regex='^(\\d{3}[- .]?){2}\\d{4}$')])),
                ('persons', models.PositiveSmallIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=10, validators=[django.core.validators.RegexValidator(message='dd/mm/yyyy', regex='^(3[01]|[12][0-9]|0?[1-9])/(1[0-2]|0?[1-9])/(?:[0-9]{2})?[0-9]{2}$'), main_page.models.BookATable.validate_date])),
                ('time', models.DateTimeField(max_length=5, validators=[django.core.validators.RegexValidator(message='HH:MM or 24-hour format', regex='^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$/')])),
                ('message', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
