# Generated by Django 4.0.3 on 2022-03-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_alter_bookatable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='time',
            field=models.TimeField(max_length=5),
        ),
    ]
