# Generated by Django 4.0.3 on 2022-03-13 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_alter_bookatable_date_alter_bookatable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='date',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='dd/mm/yyyy', regex='^(3[01]|[12][0-9]|0?[1-9])/(1[0-2]|0?[1-9])/(?:[0-9]{2})?[0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='bookatable',
            name='time',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='HH:MM of 24-hour format', regex='^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$/')]),
        ),
    ]
